// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200428235939_Added missing items to dbset")]
    partial class Addedmissingitemstodbset
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Domain.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<int>("UserType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Domain.Memberships.Membership", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            Id = "29ad0121-b184-461b-b2c9-518355e35123",
                            Cost = 250.0,
                            Description = "Approved by Boris, loved by Slavs, misunderstood by Americans.",
                            Name = "Gopnik Workout"
                        },
                        new
                        {
                            Id = "615ca8e5-0124-4ea6-85b4-3badb4a6ec1a",
                            Cost = 100.0,
                            Description = "Simple and effective after you gorged yourself",
                            Name = "Squats and Pull Ups"
                        });
                });

            modelBuilder.Entity("Domain.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = "3a0a646e-2fa8-4ab9-b2dc-3aa2518d4e78",
                            Content = "Test Message 1",
                            DateOfMessage = new DateTime(2020, 4, 27, 19, 59, 38, 912, DateTimeKind.Local).AddTicks(7927),
                            From = "Anna Runner",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = "d1940fcc-f86a-4b48-ad97-3f7ff1321647",
                            Content = "Test Message 2",
                            DateOfMessage = new DateTime(2020, 4, 28, 19, 59, 38, 915, DateTimeKind.Local).AddTicks(1647),
                            From = "Michael Kovalsky",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = "b92e0a10-33e1-4108-be76-c1ec87677330",
                            Content = "Test Message 3",
                            DateOfMessage = new DateTime(2020, 4, 26, 19, 59, 38, 915, DateTimeKind.Local).AddTicks(1679),
                            From = "Aaron Runner",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Domain.Workouts.Exercise", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseGroupId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = "3ed05cf8-b64a-4af9-ab63-dda3dbd7a4ae",
                            ExerciseGroupId = "2b60f7f4-09c5-403c-882b-eadf0bf912d0",
                            Reps = 4
                        },
                        new
                        {
                            Id = "8bc0d4fb-26e6-4b41-b490-a50791ab436d",
                            ExerciseGroupId = "2b60f7f4-09c5-403c-882b-eadf0bf912d0",
                            Reps = 4
                        },
                        new
                        {
                            Id = "c0d31a48-98e5-4d6d-b5d3-610cefc2c1bc",
                            ExerciseGroupId = "2b60f7f4-09c5-403c-882b-eadf0bf912d0",
                            Reps = 3
                        },
                        new
                        {
                            Id = "68a4f026-8849-479a-b8ae-0d477667d32a",
                            ExerciseGroupId = "adf78c99-8106-49df-b0dd-d0b145ddc53e",
                            Reps = 4
                        },
                        new
                        {
                            Id = "47a712e6-2d2e-4e8c-b527-c234c78d326c",
                            ExerciseGroupId = "adf78c99-8106-49df-b0dd-d0b145ddc53e",
                            Reps = 4
                        },
                        new
                        {
                            Id = "b14d407d-ea70-4989-ba86-7dc7355dfa95",
                            ExerciseGroupId = "adf78c99-8106-49df-b0dd-d0b145ddc53e",
                            Reps = 3
                        },
                        new
                        {
                            Id = "860da657-a708-48f1-ad65-54c15b23e736",
                            ExerciseGroupId = "ba596bca-7603-4d16-b9bc-aae93a414330",
                            Reps = 4
                        },
                        new
                        {
                            Id = "2f3140cc-4149-42c8-a42f-caca2c87cbcc",
                            ExerciseGroupId = "ba596bca-7603-4d16-b9bc-aae93a414330",
                            Reps = 4
                        },
                        new
                        {
                            Id = "5c976509-bda4-457d-87dc-dfcde786babc",
                            ExerciseGroupId = "ba596bca-7603-4d16-b9bc-aae93a414330",
                            Reps = 3
                        });
                });

            modelBuilder.Entity("Domain.Workouts.ExerciseGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pace")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkoutId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("ExerciseGroups");

                    b.HasData(
                        new
                        {
                            Id = "2b60f7f4-09c5-403c-882b-eadf0bf912d0",
                            Name = "DB Hang Snatch",
                            Pace = "x-safe",
                            Sets = 4,
                            WorkoutId = "ba596bca-7603-4d16-b9bc-aae93a414330"
                        },
                        new
                        {
                            Id = "adf78c99-8106-49df-b0dd-d0b145ddc53e",
                            Name = "Goblet Front Squat",
                            Pace = "safe-x",
                            Sets = 4,
                            WorkoutId = "ba596bca-7603-4d16-b9bc-aae93a414330"
                        },
                        new
                        {
                            Id = "6bcc3b40-17e5-440a-9f5f-98bdbb73f7f7",
                            Name = "DB RDL",
                            Pace = "3-1-x",
                            Sets = 4,
                            WorkoutId = "ba596bca-7603-4d16-b9bc-aae93a414330"
                        });
                });

            modelBuilder.Entity("Domain.Workouts.Workout", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfWorkout")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("MembershipId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = "ba596bca-7603-4d16-b9bc-aae93a414330",
                            DateOfWorkout = new DateTime(2020, 4, 28, 19, 59, 38, 916, DateTimeKind.Local).AddTicks(6358),
                            Description = "Regular push ups",
                            MembershipId = "29ad0121-b184-461b-b2c9-518355e35123",
                            Name = "Gopnik One"
                        },
                        new
                        {
                            Id = "5f2ed3f1-a767-4803-b612-d3f04e508cc1",
                            DateOfWorkout = new DateTime(2020, 4, 28, 19, 59, 38, 916, DateTimeKind.Local).AddTicks(8527),
                            Description = "",
                            MembershipId = "615ca8e5-0124-4ea6-85b4-3badb4a6ec1a",
                            Name = "Squat One"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Domain.Workouts.Exercise", b =>
                {
                    b.HasOne("Domain.Workouts.ExerciseGroup", "ExerciseGroup")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseGroupId");
                });

            modelBuilder.Entity("Domain.Workouts.ExerciseGroup", b =>
                {
                    b.HasOne("Domain.Workouts.Workout", "Workout")
                        .WithMany("ExerciseGroups")
                        .HasForeignKey("WorkoutId");
                });

            modelBuilder.Entity("Domain.Workouts.Workout", b =>
                {
                    b.HasOne("Domain.Memberships.Membership", "Membership")
                        .WithMany("Workouts")
                        .HasForeignKey("MembershipId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
